- name: Run Bot
  env:
    EMAIL_ID: ${{ secrets.EMAIL_ID }}
    EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
    GOOGLE_SHEET_NAME: ${{ secrets.GOOGLE_SHEET_NAME }}
    GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

  run: |
    echo "===== CURRENT DIRECTORY ====="
    pwd

    echo "===== FILES ====="
    ls -la

    echo "===== MAIN.PY CONTENT ====="
    cat main.py

    echo "===== RUNNING ====="
    python main.py
